baseURL = 'https://getmakingthings.com/'
languageCode = 'en-us'
title = 'Making Things LLC'

[params]
  tagline = 'We build iOS apps people love to use.'
  company = 'Making Things LLC'
  email = 'support@getmakingthings.com'

[menus]
  [[menus.main]]
    name = 'Apps'
    pageRef = '/apps'
    weight = 10
  [[menus.main]]
    name = 'About'
    pageRef = '/about'
    weight = 20
